# Licensed to Elasticsearch B.V. under one or more contributor
# license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright
# ownership. Elasticsearch B.V. licenses this file to you under
# the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

require 'bundler/gem_tasks'
require 'rake/testtask'
require 'rspec/core/rake_task'

task :default do
  exec "rake --tasks"
end

Rake::TestTask.new('test:unit') do |test|
  test.libs << 'test'
  test.test_files = FileList['test/unit/**/*_test.rb']
  test.verbose = false
  test.warning = false
end

# TODO: Temporarily Kept for backwards compatibility with ../rake_tasks/test_tasks.rake
desc 'Run integration tests'
task :integration

namespace :test do
  desc 'Run REST API YAML tests'
  RSpec::Core::RakeTask.new(:rest_api) do |t|
    ENV['TEST_SUITE'] = 'platinum'
    t.pattern = 'spec/xpack/rest_api_yaml_spec.rb'
  end

  RSpec::Core::RakeTask.new(:spec) do |t|
    t.pattern = 'spec/xpack/**/*_spec.rb'
    t.exclude_pattern = 'spec/xpack/rest_api_yaml_spec.rb'
  end

  desc "Run integration tests"
  task :integration do
    Rake::Task['test:rest_api'].invoke
  end

  desc "Run all tests"
  task :all do
    Rake::Task['test:unit'].invoke
    Rake::Task['test:spec'].invoke
    Rake::Task['test:rest_api'].invoke
  end
end
