source 'https://rubygems.org'

# Specify your gem's dependencies in elasticsearch-watcher.gemspec
gemspec

gem 'elasticsearch', :path => '../elasticsearch'
gem 'elasticsearch-extensions', :path => '../elasticsearch-extensions'
