source 'https://rubygems.org'

# Specify your gem's dependencies in elasticsearch-api.gemspec
gemspec

if File.exists? File.expand_path("../../elasticsearch-extensions", __FILE__)
  gem 'elasticsearch-extensions', :path => File.expand_path("../../elasticsearch-extensions", __FILE__), :require => true
end

if File.exists? File.expand_path("../../elasticsearch-transport", __FILE__)
  gem 'elasticsearch-transport', :path => File.expand_path("../../elasticsearch-transport", __FILE__), :require => true
end
