[[release_notes_717]]
=== 7.17 Release notes

[discrete]
[[release_notes_71711]]
=== 7.17.11 Release notes

- Ruby 3.3 added to the test matrix. Tested versions of Ruby for 7.17.11: Ruby (MRI) 3.0, 3.1, 3.2, 3.3, JRuby 9.3, JRuby 9.4.
- Adds `base64` dependency to `elasticsearch-transport`: base64 was added to the gemspec, since starting in Ruby 3.4.0, base64 will no longer be part of the default gems and will no longer be in the standard library,  https://github.com/elastic/elasticsearch-ruby/pull/2400[#2400].

[discrete]
[[release_notes_71710]]
=== 7.17.10 Release notes

Backports support for Faraday 2 from `elastic-transport`. ¡Gracias https://github.com/santiagorodriguez96[santiagorodriguez96]!

This version of the gem now supports Faraday v2. If you don't have a locked version of Faraday in your project, when you upgrade your gems, Faraday v2 will be installed. The main change on dependencies when using Faraday v2 is all adapters, except for the default `net_http` one, have been moved out of Faraday into separate gems. This means if you're not using the default adapter and you migrate to Faraday v2, you'll need to add the adapter gems to your Gemfile.

These are the gems required for the different adapters with Faraday 2, instead of the libraries on which they were based:

[source,ruby]
------------------------------------
# HTTPCLient
gem 'faraday-httpclient'

# NetHTTPPersistent
gem 'faraday-net_http_persistent'

# Patron
gem 'faraday-patron'

# Typhoeus
gem 'faraday-typhoeus'
------------------------------------

Things should work fine if you migrate to Faraday 2 as long as you include the adapter (unless you're using the default one `net-http`), but worst case scenario, you can always lock the version of Faraday in your project to 1.x:
gem 'faraday', '~> 1'

Be aware if migrating to Faraday v2 that it requires at least Ruby `2.6`, unlike Faraday v1 which requires `2.4`.

*Troubleshooting*

If you see a message like:

[source,ruby]
------------------------------------
:adapter is not registered on Faraday::Adapter (Faraday::Error)
------------------------------------
Then you probably need to include the adapter library in your gemfile and require it.

Please https://github.com/elastic/elasticsearch-ruby/issues[submit an issue] if you encounter any problems.

[discrete]
[[release_notes_7179]]
=== 7.17.9 Release notes

- Backports fix from `elastic-transport`, fixes https://github.com/elastic/elastic-transport-ruby/issues/66[#66]: Manticore transport unable to send custom headers with `perform_request` https://github.com/elastic/elastic-transport-ruby/pull/69[Pull Request].

[discrete]
[[release_notes_7178]]
=== 7.17.8 Release notes

- Patch releases back to being detached from Elastic stack releases.
- Tested compatibility with latest releases of Elasticsearch v7.17 APIs.
- Tested versions of Ruby for 7.17.8: Ruby (MRI) 2.7, 3.0, 3.1, 3.2, JRuby 9.3, JRuby 9.4.
- Bugfix in elasticsearch-transport: Fixes enforcing UTF-8 in Response body, causing an error when the string is frozen, particularly when using webmock: https://github.com/elastic/elastic-transport-ruby/issues/63[issue #63].


[discrete]
[[release_notes_7177]]
=== 7.17.7 Release notes

- Compatibility with Elasticsearch v7.17.7 APIs.
- Tested versions of Ruby for 7.17.7: Ruby (MRI) 2.6, 2.7, 3.0 and 3.1, JRuby 9.3.


[discrete]
[[release_notes_7172]]
=== 7.17.2, 7.17.3, 7.17.4, 7.17.5, 7.17.6 Release notes

No release.


[discrete]
[[release_notes_7171]]
=== 7.17.1 Release notes

- Improves handling of YAML parsing, uses `safe_load` instead of `load` when doing the product verification (should only affect Ruby < 3.0).
- Updates headers setup when using the Manticore adapter. This fixes an issue where the user-agent header was being foverridden even when it was being set on initialization via the transport options. https://github.com/elastic/elasticsearch-ruby/pull/1685[Pull Request], https://github.com/elastic/elasticsearch-ruby/issues/1684[issue].

[discrete]
[[release_notes_7170]]
=== 7.17.0 Release notes

- Drops Ruby 2.5 from the test matrix. Support for Ruby 2.5 was dropped March 2021.
- Updates the product verification when the response is a `413` error.
