[[release_notes_8110]]
=== 8.11 Release notes

[discrete]
[[release_notes_8_11_1]]
=== 8.11.1 Release notes

Adds `base64` dependency

base64 was added to the gemspec, since starting in Ruby 3.4.0, base64 will no longer be part of the default gems and will no longer be in the standard library.

base64 is used forAPI key and Cloud ID. The dependency used to be declared in transport, but it's not needed there since the implementation using it is in this codebase.


[discrete]
[[release_notes_811_0]]
=== 8.11.0 Release notes

[discrete]
=== Client

* Tested versions of Ruby for 8.11.0: Ruby (MRI) 3.0, 3.1 and 3.2. JRuby 9.3 and JRuby 9.4.
* Adds native support for *Open Telemetry*. See <<opentelemetry>> for documentation.
* Improved documentation, now you can find more examples in Ruby in the https://www.elastic.co/guide/en/elasticsearch/reference/8.11/rest-apis.html[REST API reference].

[discrete]
=== API

New Experimental APIs:

* `esql.query` - Executes an ESQL request.
* `inference.delete_model` - Delete model in the Inference API
* `inference.get_model` - Get a model in the Inference API
* `inference.inference` - Perform inference on a model
* `inference.put_model` - Configure a model for use in the Inference API
