steps:
  - label: ":elasticsearch: :ruby: ES Ruby ({{ matrix.ruby }}) Test Suite: {{ matrix.suite }}"
    agents:
      provider: "gcp"
    env:
      RUBY_VERSION: "{{ matrix.ruby }}"
      TEST_SUITE: "{{ matrix.suite }}"
      STACK_VERSION: 8.5.3
    matrix:
      setup:
        suite:
          - "free"
          - "platinum"
        ruby:
          - "3.1"
          - "3.0"
          - "2.7"
    command: ./.buildkite/run-tests.sh
