steps:
  - label: ":ruby: Elasticsearch Ruby :ruby:"
    command: "echo 'First pipeline for Elasticsearch Ruby!'"
  - label: ":elasticsearch: Run Elasticsearch"
    agents:
      provider: "gcp"
    env:
      DETACH: true
    command: ./.buildkite/run-elasticsearch.sh
