steps:
  - label: ":elasticsearch: :ruby: Elasticsearch Ruby"
    agents:
      provider: "gcp"
    env:
      RUBY_VERSION: "{{ matrix }}"
    matrix:
      - "3.1"
      - "2.7"
    command: ./.buildkite/run-tests.sh
