steps:
  - label: >-
      :yaml: YAML test suite :ruby: {{ matrix.ruby_source}}:{{ matrix.ruby }}
      :phone: Transport {{ matrix.transport }}
    agents:
      provider: gcp
    matrix:
      setup:
        ruby:
          - '3.4'
          - '3.3'
          - '3.2'
        ruby_source:
          - ruby
        transport:
          - '8.4'
      adjustments:
        - with: # JRuby tests
            ruby: '9.4'
            ruby_source: jruby
            transport: '8.4'
        - with: # Test for main branch of transport
            ruby: '3.4'
            ruby_source: ruby
            transport: main
    env:
      RUBY_VERSION: '{{ matrix.ruby }}'
      STACK_VERSION: 9.1.6-SNAPSHOT
      ES_YAML_TESTS_BRANCH: '9.1'
      TRANSPORT_VERSION: '{{ matrix.transport }}'
      RUBY_SOURCE: '{{ matrix.ruby_source }}'
      TEST_SUITE: platinum
      DEBUG: true
    command: ./.buildkite/run-yaml-tests.sh
    artifact_paths: elasticsearch-api/tmp/*
  - wait: ~
    continue_on_failure: true
  - label: Log Results
    command: ./.buildkite/log-results.sh
