#!/usr/bin/env bash

#
# Runs the client tests via Docker with the expectation that the required
# environment variables have already been exported before running this script.
#
# The required environment variables include:
#
#   - $TEST_SUITE
#

sh .ci/docker/run-tests-${TEST_SUITE}