#!/usr/bin/env bash

#
# Runs the client tests via Docker with the expectation that the required
# environment variables have already been exported before running this script.
#
# The required environment variables include:
#
#   - $ELASTICSEARCH_VERSION
#   - $RUBY_TEST_VERSION
#
# Run with:
# $ ELASTICSEARCH_VERSION=6.7.0 RUBY_TEST_VERSION=2.6 sh .ci/run-tests-raw

set -eo pipefail

set +x
export VAULT_TOKEN=$(vault write -field=token auth/approle/login role_id="$VAULT_ROLE_ID" secret_id="$VAULT_SECRET_ID")
export CODECOV_TOKEN=$(vault read -field=token secret/clients-ci/elasticsearch-ruby/codecov)
unset VAULT_ROLE_ID VAULT_SECRET_ID VAULT_TOKEN
set -x

function cleanup {
  docker container rm --force --volumes elasticsearch > /dev/null 2>&1 || true
  docker container rm --force --volumes elasticsearch-2 > /dev/null 2>&1 || true
  docker container rm --force --volumes elasticsearch-ruby > /dev/null 2>&1 || true
  docker network rm esnet > /dev/null
}

trap cleanup EXIT

# create network and volume
docker network create esnet

# create client image
docker build \
  --file .ci/Dockerfile \
  --tag elastic/elasticsearch-ruby \
  --build-arg RUBY_TEST_VERSION=${RUBY_TEST_VERSION} \
  .


# run elasticsearch
docker run \
  --rm \
  --env "node.attr.testattr=test" \
  --env "path.repo=/tmp" \
  --env "repositories.url.allowed_urls=http://snapshot.*" \
  --env "http.port=9200" \
  --env "discovery.zen.minimum_master_nodes=2" \
  --env "discovery.zen.ping.unicast.hosts=elasticsearch" \
  --network=esnet \
  --name=elasticsearch \
  --detach \
  docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}

# run elasticsearch-2
docker run \
  --rm \
  --env "node.attr.testattr=test" \
  --env "path.repo=/tmp" \
  --env "repositories.url.allowed_urls=http://snapshot.*" \
  --env "http.port=9201" \
  --env "discovery.zen.minimum_master_nodes=2" \
  --env "discovery.zen.ping.unicast.hosts=elasticsearch" \
  --network=esnet \
  --name=elasticsearch-2 \
  --detach \
  docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}

# run the client tests
docker run \
  --network=esnet \
  --env "TEST_ES_SERVER=http://elasticsearch:9200" \
  --env "CODECOV_TOKEN" \
  --volume $repo:/usr/src/app \
  --name elasticsearch-ruby \
  --rm \
  elastic/elasticsearch-ruby \
  bundle exec rake test:client


