# Licensed to Elasticsearch B.V under one or more agreements.
# Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
# See the LICENSE file in the project root for more information

source 'https://rubygems.org'

gem 'activesupport'
gem 'rest-client'
gem 'coderay'
gem 'multi_json'
gem 'thor'
gem 'json'
gem 'pry'
gem 'rubocop'
