source 'https://rubygems.org'

# Specify your gem's dependencies in elasticsearch-extensions.gemspec
gemspec

if File.exists? File.expand_path("../../elasticsearch/elasticsearch.gemspec", __FILE__)
  gem 'elasticsearch', :path => File.expand_path("../../elasticsearch/", __FILE__)
end
