source 'https://rubygems.org'

# Specify your gem's dependencies in elasticsearch-extensions.gemspec
gemspec

gem 'elasticsearch-api', :path => "../elasticsearch-api", :require => false
gem 'elasticsearch-transport', :path => "../elasticsearch-transport", :require => false
gem 'elasticsearch-extensions', :path => "../elasticsearch-extensions", :require => false

gem 'elasticsearch', :path => "../elasticsearch/"
