source 'https://rubygems.org'

# Specify your gem's dependencies in elasticsearch.gemspec
gemspec

if File.exists? File.expand_path("../../elasticsearch-extensions", __FILE__)
  gem 'elasticsearch-extensions', :path => File.expand_path("../../elasticsearch-extensions", __FILE__), :require => true
end
