#!/usr/bin/env bash

#
# Runs the client tests via Docker with the expectation that the required
# environment variables have already been exported before running this script.
#
# The required environment variables include:
#
#   - $ELASTICSEARCH_VERSION
#
repo=`pwd`

# run the client tests
docker run \
  --network="${NETWORK_NAME}" \
  --env "TEST_ES_SERVER=http://elasticsearch:9200" \
  --volume $repo:/usr/src/app \
  --volume=/tmp:/tmp \
  --name elasticsearch-ruby \
  --rm \
  elastic/elasticsearch-ruby \
  bundle exec rake test:rest_api
