#!/usr/bin/env bash

#
# Runs the client tests via Docker with the expectation that the required
# environment variables have already been exported before running this script.
#
# The required environment variables include:
#
#   - $ELASTICSEARCH_VERSION
#
repo=$(pwd)

# run the security (xpack) tests
docker run \
  --network="${NETWORK_NAME}" \
  --env "TEST_ES_SERVER=elasticsearch:9200" \
  --env "ELASTIC_PASSWORD=changeme" \
  --env "ELASTIC_USER=elastic" \
  --env "TEST_SUITE=security" \
  --env "SINGLE_TEST=${SINGLE_TEST}" \
  --volume $repo:/usr/src/app \
  --name elasticsearch-ruby \
  --rm \
  elastic/elasticsearch-ruby \
  bundle exec rake test:security
