[[ruby-install]]
== Installation

Install the Rubygem for the latest {es} version by using the following command:

[source,sh]
------------------------------------
gem install elasticsearch
------------------------------------


Or add the `elasticsearch` Ruby gem to your Gemfile:

[source,ruby]
------------------------------------
gem 'elasticsearch'
------------------------------------



You can install the Ruby gem for a specific {es} version by using the following 
command:

[source,sh]
------------------------------------
gem install elasticsearch -v 7.0.0
------------------------------------


Or you can add a specific version of {es} to your Gemfile:

[source,ruby]
------------------------------------
gem 'elasticsearch', '~> 7.0'
------------------------------------


[discrete]
=== {es} and Ruby Version Compatibility

The {es} client is compatible with currently maintained Ruby versions. We follow Ruby’s own maintenance policy and officially support all currently maintained versions per https://www.ruby-lang.org/en/downloads/branches/[Ruby Maintenance Branches].

Language clients are forward compatible; meaning that clients support communicating with greater or equal minor versions of {es}. Elasticsearch language clients are only backwards compatible with default distributions and without guarantees made.
