[[ruby-install]]
== Installation

Install the Rubygem for the latest {es} version by using the following command:

[source,sh]
------------------------------------
gem install elasticsearch
------------------------------------


Or add the `elasticsearch` Ruby gem to your Gemfile:

[source,ruby]
------------------------------------
gem 'elasticsearch'
------------------------------------



You can install the Ruby gem for a specific {es} version by using the following 
command:

[source,sh]
------------------------------------
gem install elasticsearch -v 7.0.0
------------------------------------


Or you can add a specific version of {es} to your Gemfile:

[source,ruby]
------------------------------------
gem 'elasticsearch', '~> 7.0'
------------------------------------


[discrete]
=== {es} and Ruby Version Compatibility

The {es} client is compatible with currently maintained Ruby versions. We follow Ruby’s own maintenance policy and officially support all currently maintained versions per https://www.ruby-lang.org/en/downloads/branches/[Ruby Maintenance Branches].

Language clients are forward compatible; meaning that clients support communicating with greater minor versions of {es}. Elastic language clients are also backwards compatible with lesser supported minor {es} versions.

|===
| Gem Version   |   | {es} Version

| 0.90          | → | 0.90
| 1.x           | → | 1.x
| 2.x           | → | 2.x
| 5.x           | → | 5.x
| 6.x           | → | 6.x
| 7.x           | → | 7.x
| master        | → | master
|===
