name: master
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test-master:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.5, 2.6, 2.7, jruby ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build
      run: |
        sudo apt-get update
        sudo apt-get install libcurl4-openssl-dev
        rake bundle:clean
        rake bundle:install
    - name: Test with Rake
      run: rake test:unit
